CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS CITIES (
    CITY_ID SERIAL PRIMARY KEY,
    CITY VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ZIP_CODES (
    ZIP_CODE_ID SERIAL PRIMARY KEY,
    ZIP_CODE VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS DESCRIPTIONS (
    DESCRIPTION_ID SERIAL PRIMARY KEY,
    DESCRIPTION_TEXT VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS LAST_NAMES (
    LAST_NAME_ID SERIAL PRIMARY KEY,
    LAST_NAME VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS FIRST_NAMES (
    FIRST_NAME_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS STATES (
    STATE_ID SERIAL PRIMARY KEY,
    STATE CHAR(2) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROVIDER_RECORDS (
    PROVIDER_UUID UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    DESCRIPTION_ID INT NOT NULL,
    CITY_ID INT NOT NULL,
    FIRST_NAME_ID INT NOT NULL,
    LAST_NAME_ID INT NOT NULL,
    ZIP_CODE_ID INT NOT NULL,
    STATE_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE(CITY_ID, FIRST_NAME_ID, LAST_NAME_ID, ZIP_CODE_ID, DESCRIPTION_ID, STATE_ID),
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID),
    FOREIGN KEY (ZIP_CODE_ID) REFERENCES ZIP_CODES(ZIP_CODE_ID),
    FOREIGN KEY (DESCRIPTION_ID) REFERENCES DESCRIPTIONS(DESCRIPTION_ID),
    FOREIGN KEY (LAST_NAME_ID) REFERENCES LAST_NAMES(LAST_NAME_ID),
    FOREIGN KEY (FIRST_NAME_ID) REFERENCES FIRST_NAMES(FIRST_NAME_ID),
    FOREIGN KEY (STATE_ID) REFERENCES STATES(STATE_ID)
);