CREATE TABLE ADDRESSES (
    ADDRESS_ID SERIAL PRIMARY KEY,
    STREET VARCHAR(75) NOT NULL,
    ZIP_CODE VARCHAR(9) NOT NULL,
    STATE CHAR(2) NOT NULL DEFAULT 'XX',
    CITY_NAME VARCHAR UNIQUE NOT NULL DEFAULT 'N/A'
);

CREATE TABLE IF NOT EXISTS TAXONOMIES (
    TAXONOMY_CODE CHAR(10) PRIMARY KEY,
    TAXONOMY_DESCRIPTION VARCHAR NOT NULL,
    TAXONOMY_SPECIALIZATION VARCHAR NOT NULL,
    UNIQUE(TAXONOMY_CODE, TAXONOMY_SPECIALIZATION)
);

CREATE TABLE IF NOT EXISTS NPI_TO_TAXONOMIES (
    NPI NUMERIC(10),
    TAXONOMY_CODE CHAR(10),
    PRIMARY KEY (NPI, TAXONOMY_CODE),
    FOREIGN KEY (TAXONOMY_CODE) REFERENCES TAXONOMIES(TAXONOMY_CODE)
);

CREATE TABLE IF NOT EXISTS MEDICAL_PROVIDERS (
    NPI NUMERIC(10) PRIMARY KEY,
    PHONE_NUMBER CHAR(10) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR NOT NULL,
    MIDDLE_NAME VARCHAR NOT NULL DEFAULT 'N/A',
    LAST_NAME VARCHAR NOT NULL,
    PRIMARY_ADDRESS_ID INT NOT NULL,
    FOREIGN KEY (PRIMARY_ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    FOREIGN KEY (NPI) REFERENCES NPI_TO_TAXONOMIES(NPI) ON DELETE CASCADE
);

--- TEST EXAMPLE