CREATE TABLE STREETS (
    STREET_ID SERIAL PRIMARY KEY,
    STREET_NAME VARCHAR NOT NULL,
    UNIT VARCHAR NOT NULL,
    UNIQUE(STREET_NAME, UNIT)
);

CREATE TABLE STATES (
    STATE_ID SERIAL PRIMARY KEY,
    STATE_ABBR CHAR(2) UNIQUE NOT NULL DEFAULT 'XX'
);

CREATE TABLE CITIES (
    CITY_ID SERIAL PRIMARY KEY,
    CITY_NAME VARCHAR UNIQUE NOT NULL DEFAULT 'N/A',
    STATE_ID INT NOT NULL DEFAULT 1,
    FOREIGN KEY (STATE_ID) REFERENCES STATES(STATE_ID),
    UNIQUE(CITY_NAME, STATE_ID)
);

CREATE TABLE ZIP_CODES (
    ZIP_CODE VARCHAR(10) PRIMARY KEY,
    CITY_ID INT NOT NULL DEFAULT 1,
    FOREIGN KEY (CITY_ID) REFERENCES CITIES(CITY_ID),
    UNIQUE(CITY_ID, ZIP_CODE),
    CHECK((ZIP_CODE ~ '^\d{5}$') OR (ZIP_CODE ~ '^\d{9}$'))
);

CREATE TABLE ADDRESSES (
    ADDRESS_ID SERIAL PRIMARY KEY,
    STREET_ID INT NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    FOREIGN KEY (STREET_ID) REFERENCES STREETS(STREET_ID),
    FOREIGN KEY (ZIP_CODE) REFERENCES ZIP_CODES(ZIP_CODE),
    UNIQUE(STREET_ID, ZIP_CODE)
);

CREATE TABLE FULL_NAMES (
    FULL_NAME_ID SERIAL PRIMARY KEY,
    FIRST_NAME VARCHAR NOT NULL DEFAULT 'N/A',
    MIDDLE_NAME VARCHAR NOT NULL DEFAULT 'N/A',
    LAST_NAME VARCHAR NOT NULL DEFAULT 'N/A',
    UNIQUE(FIRST_NAME, MIDDLE_NAME, LAST_NAME)
);

--- INSERT "NULL" VALUES FIRST AS ITS OWN COLUMN TO BE REFERENCED AS 1 FOR ALL IDs (not UUID).
INSERT INTO STREETS DEFAULT VALUES;

INSERT INTO CITIES DEFAULT VALUES;

INSERT INTO STATES DEFAULT VALUES;

INSERT INTO ZIP_CODES (ZIP_CODE, CITY_ID, STATE_ID)
VALUES (DEFAULT, 1, 1);

INSERT INTO ADDRESSES (STREET_ID, ZIP_CODE_ID)
VALUES (1, 1);

INSERT INTO FULL_NAMES DEFAULT VALUES;

--- END COMMENT
CREATE TABLE IF NOT EXISTS MEDICAL_PROVIDERS (
    NPI INT PRIMARY KEY,
    DESCRIPTION_NAME VARCHAR NOT NULL,
    PHONE_NUMBER CHAR(10) UNIQUE NOT NULL,
    FULL_NAME_ID INT NOT NULL,
    PRIMARY_ADDRESS_ID INT NOT NULL,
    SECONDARY_ADDRESS_ID INT NOT NULL DEFAULT 1,
    FOREIGN KEY (FULL_NAME_ID) REFERENCES FULL_NAMES(FULL_NAME_ID),
    FOREIGN KEY (PRIMARY_ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID),
    FOREIGN KEY (SECONDARY_ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);

--- TEST EXAMPLE
INSERT INTO STREET_NUMBERS(STREET_NUMBER)
VALUES('123');

INSERT INTO STREET_NAMES(STREET_NAME)
VALUES('Main');

INSERT INTO STREET_TYPES(STREET_TYPE)
VALUES('St');

INSERT INTO STREETS (STREET_NUMBER_ID, STREET_NAME_ID, STREET_TYPE_ID, UNIT_TYPE_ID, UNIT_NUMBER_ID)
VALUES (2, 2, 2, 1, 1);

INSERT INTO CITIES (CITY)
VALUES ('Springfield');
INSERT INTO CITIES (CITY)
VALUES ('Chicago');
INSERT INTO STATES (STATE)
VALUES ('IL');

INSERT INTO ZIP_CODES (CITY_ID, STATE_ID, ZIP_CODE)
VALUES (2, 2, 62701);
INSERT INTO ZIP_CODES (CITY_ID, STATE_ID, ZIP_CODE)
VALUES (2, 2, 62704);

INSERT INTO ADDRESSES (STREET_ID, ZIP_CODE_ID)
VALUES (2, 2);

INSERT INTO FIRST_NAMES (FIRST_NAME)
VALUES ('John');

INSERT INTO LAST_NAMES (LAST_NAME)
VALUES ('Smith');

INSERT INTO DESCRIPTIONS (DESCRIPTION)
VALUES ('Cardiologist');

INSERT INTO AREA_CODES (AREA_CODE)
VALUES (555);

INSERT INTO EXCHANGE_CODES (EXCHANGE_CODE)
VALUES (123);

INSERT INTO SUBSCRIBE_NUMBERS (SUBSCRIBE_NUMBER)
VALUES (4567);

INSERT INTO PHONE_NUMBERS (AREA_CODE_ID, EXCHANGE_CODE_ID, SUBSCRIBE_NUMBER_ID)
VALUES (2, 2, 2);

INSERT INTO MEDICAL_PROVIDERS (
    FIRST_NAME_ID, 
    LAST_NAME_ID, 
    DESCRIPTION_ID, 
    PHONE_NUMBER_ID, 
    PRIMARY_ADDRESS_ID
) VALUES (
    2, 2, 2, 2, 2
);
--- END TEST