# Generated by Django 5.2.3 on 2025-06-11 17:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city_id', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('city', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('description_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description_id', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('description_text', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirstName',
            fields=[
                ('first_name_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name_id', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('first_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LastName',
            fields=[
                ('last_name_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name_id', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('last_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zip_code_id', models.DecimalField(decimal_places=0, max_digits=20, unique=True)),
                ('zip_code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderRecord',
            fields=[
                ('provider_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.city', to_field='city_id')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.description', to_field='description_id')),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.firstname', to_field='first_name_id')),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.lastname', to_field='last_name_id')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.zipcode', to_field='zip_code_id')),
            ],
            options={
                'unique_together': {('city', 'first_name', 'last_name', 'zip_code', 'description')},
            },
        ),
    ]
