# Generated by Django 5.2.3 on 2025-06-24 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('npi', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('mailing_street', models.CharField(blank=True, max_length=224, null=True)),
                ('mailing_city', models.CharField(blank=True, max_length=64, null=True)),
                ('mailing_state', models.CharField(blank=True, max_length=64, null=True)),
                ('mailing_zip_code', models.CharField(blank=True, max_length=25, null=True)),
            ],
            options={
                'db_table': 'medical_providers',
            },
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taxonomy_code', models.CharField(max_length=10, unique=True)),
                ('taxonomy_specialization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'taxonomies',
            },
        ),
        migrations.CreateModel(
            name='NPIToTaxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('npi', models.ForeignKey(db_column='npi', on_delete=django.db.models.deletion.CASCADE, to='provider_app.medicalprovider', to_field='npi')),
                ('taxonomy_code', models.ForeignKey(db_column='taxonomy_code', on_delete=django.db.models.deletion.CASCADE, to='provider_app.taxonomy', to_field='taxonomy_code')),
            ],
            options={
                'db_table': 'npi_to_taxonomies',
                'unique_together': {('npi', 'taxonomy_code')},
            },
        ),
    ]
